name: embeddedio

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Display current directory and files
        run: |
          echo "📁 Current directory: $PWD"
          echo "📂 List of files:"
          ls -la

      - name: Determine deploy path and create directory
        run: |
          USERNAME=$(whoami)
          DEPLOY_PATH="/home/$USERNAME/public_html/embeddedio"
          echo "📁 Deploy path: $DEPLOY_PATH"
          mkdir -p "$DEPLOY_PATH"

      - name: Sync project files into deploy directory
        run: |
          USERNAME=$(whoami)
          DEPLOY_PATH="/home/$USERNAME/public_html/embeddedio"
          rsync -av --exclude='.git' ./ "$DEPLOY_PATH"/ --delete
