name: embeddedio

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Display current directory and files
        run: |
          echo "📁 Current directory: $PWD"
          echo "📂 List of files:"
          ls -la

      - name: Create html_public/embeddedio directory if it doesn't exist
        run: mkdir -p html_public/embeddedio

      - name: Sync project files into html_public/embeddedio
        run: |
          rsync -av --exclude='html_public' --exclude='.git' ./ html_public/embeddedio/ --delete
