name: embeddedio

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Display current directory and files
        run: |
          echo "📁 Current directory: $PWD"
          echo "📂 List of files:"
          ls -la
